// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNRPUbcx6lt5yBrRE72_AqumvznwWNEu8',
    appId: '1:284674971325:web:db156be8df5ba1524ec9d4',
    messagingSenderId: '284674971325',
    projectId: 'musicapp-3b725',
    authDomain: 'musicapp-3b725.firebaseapp.com',
    storageBucket: 'musicapp-3b725.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsIwhGjTmJm_jwq9vz5nqn9cAi1Rdk6i4',
    appId: '1:284674971325:android:23c004329828e9b64ec9d4',
    messagingSenderId: '284674971325',
    projectId: 'musicapp-3b725',
    storageBucket: 'musicapp-3b725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKD-o0kAGqp9k8-Ui4I3kXvXuF0rO6QTs',
    appId: '1:284674971325:ios:23e72334b14265bc4ec9d4',
    messagingSenderId: '284674971325',
    projectId: 'musicapp-3b725',
    storageBucket: 'musicapp-3b725.appspot.com',
    iosBundleId: 'com.example.spotifycleanarchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKD-o0kAGqp9k8-Ui4I3kXvXuF0rO6QTs',
    appId: '1:284674971325:ios:23e72334b14265bc4ec9d4',
    messagingSenderId: '284674971325',
    projectId: 'musicapp-3b725',
    storageBucket: 'musicapp-3b725.appspot.com',
    iosBundleId: 'com.example.spotifycleanarchitecture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNRPUbcx6lt5yBrRE72_AqumvznwWNEu8',
    appId: '1:284674971325:web:c60d8c0abfcaf8e94ec9d4',
    messagingSenderId: '284674971325',
    projectId: 'musicapp-3b725',
    authDomain: 'musicapp-3b725.firebaseapp.com',
    storageBucket: 'musicapp-3b725.appspot.com',
  );
}
